export const Home = () => (
    <>
        <div style={{fontSize: '60px', display: "flex"}}>
            Home
            {/* Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home
            Home */}
   
     
        </div>    
    </>
)